language: python

sudo: true

python:
  - 3.7

before_install:
  - docker-compose up
  - sudo apt-get install jq

install:
  - ./conf/install.sh

script:
  - coverage run -m unittest discover test
  - coverage report -m
  - coveralls