language: python

os: linux

services:
  - docker

python:
  - 3.7

before_install:
  - git clone https://github.com/eficode/wait-for.git
  - docker-compose up -d
  - cd wait-for
  - ./wait-for 127.0.0.1:7474 -t 60 -- echo "Neo4J up 1"
  - ./wait-for 127.0.0.1:7687 -t 60 -- echo "Neo4J up 2"
  - cd ..
  - sudo apt-get install jq

install:
  - ./conf/install.sh

script:
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate archgraph
  - coverage run -m unittest discover test
  - coverage report -m
  - coveralls