version: '3.3'

services:
  mongodb_container:
    container_name: mongodb_container
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    restart: on-failure
  neo4j:
    container_name: archgraph-neo4j
    image: neo4j:3.5.14
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./volumes/neo4j/data:/data
    networks:
      - archgraph-docker-deployment
    restart: on-failure<
networks:
  archgraph-docker-deployment: {}