version: '3.3'

services:
  mongodb:
    container_name: archgraph-mongodb
    image: library/mongo:4.2.1
    command: ["--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - archgraph-docker-deployment
    restart: on-failure
  neo4j:
    container_name: archgraph-neo4j
    image: neo4j:3.5.14
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./volumes/neo4j/data:/data
    networks:
      - archgraph-docker-deployment
    restart: on-failure
  archgraph:
      container_name: archgraph
      image: feupinfolab/archgraph:latest
      build:
        dockerfile: Dockerfile
        args:
          SOURCE_BRANCH: "master"
        context: .
      environment:
        - "NEO4J_HOST=archgraph-neo4j"
        - "NEO4J_PORT=7687"
        - "MONGODB_HOST=mongodb"
        - "MONGODB_PORT=27017"
        - "CUSTOM_HOST_FOR_SERVER_BIND=0.0.0.0"
        - "RUN_IN_PRODUCTION=1"
        - "INIT_GRAPH=1"
        - "FORCE_RELOAD_GRAPH=0"
      ports:
        - published: 4200
          target: 4200
        - published: 5000
          target: 5000
      depends_on:
        - mongodb
        - neo4j
      networks:
        - archgraph-docker-deployment
      restart: on-failure
networks:
  archgraph-docker-deployment: {}
