version: '3.3'

services:
  mongodb:
    container_name: archgraph-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    restart: on-failure
  neo4j:
    container_name: archgraph-neo4j
    image: neo4j:3.5.14
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./volumes/neo4j/data:/data
    networks:
      - archgraph-docker-deployment
    restart: on-failure
  archgraph:
      container_name: archgraph
      image: feupinfolab/archgraph:latest
      build:
        dockerfile: Dockerfile
        args:
          - "SOURCE_BRANCH=master"
          - "PRELOAD_GRAPH=1"
        context: .
      environment:
        - "NEO4J_CONNECTION_STRING=bolt://neo4j:password@neo4j:7687"
        - "RUN_IN_PRODUCTION=1"

      ports:
        - published: 4200
          target: 4200
        - published: 5000
          target: 5000
      depends_on:
        - mongodb
        - neo4j
      networks:
        - archgraph-docker-deployment
      restart: on-failure
networks:
  archgraph-docker-deployment: {}
