version: '3.3'

services:
  fuseki:
    container_name: archgraph-fuseki
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=pw123
      - JVM_ARGS=-Xmx2g
      - FUSEKI_DATASET_1=ds
    ports:
      - 3030:3030
    volumes:
      - ./volumes/fuseki:/staging
    restart: on-failure
