version: "3.3"
services:
  fuseki:
    container_name: archgraph-fuseki
    image: blankdots/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - 3030:3030
    volumes:
      - ./volumes/fuseki:/staging
    restart: on-failure
