version: "3.3"
services:
  fuseki:
    container_name: fuseki
    image: blankdots/jena-fuseki
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - 3030:3030
    volumes:
      - ./volumes/fuseki:/staging
    restart: on-failure
    networks:
      - app
  webservice:
    container_name: webservice
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./volumes/web-service:/data
    restart: on-failure
    networks:
      - app
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - fuseki
    restart: on-failure
    networks:
      - app
networks:
  app: {}


#new_project_backend ->
#blankdots/jena-fuseki->
#docker network connect new_project_app backend
#docker network connect new_project_app fuseki
#docker network connect new_project_app webservice
#
# docker inspect network new_project_app

#docker-compose build backend
#
# docker stop $(docker ps -a -q)
# docker rm $(docker ps -a -q)

# docker network prune
#
#docker run -itd  --network my_network backend
#docker run -itd  --network my_network fuseki
#docker run -itd  --network my_network webservice
#
#
#new_project_web-service -> docker run -itd --name webservice -p 4200:4200 --network my_network new_project_web-service ash